@startuml

entity User {
    + id [PK]
    ---
    user_id(表示用)
    user_name
    email
    country
    birthday
    instagram_id
    deleted
    created_at
    updated_at
}

entity UserProfile {
    + id [PK]
    ---
    # user_id [FK]
    created_at
    updated_at
}

entity Setting {
    + id [PK]
    ---
    # user_id [FK]
    is_notify
    created_at
    updated_at
}

entity Post {
    + id [PK]
    ---
    # user_id [FK]
    # sake_id [FK]
    content
    image
    cerated_at
    updated_at
}

entity Comment {
    + id [PK]
    ---
    # post_id [FK]
    # user_id [FK]
    content
    created_at
    updated_at
}

entity Sake {
    + id [PK]
    ---
    sake_name
    kuramoto
    prefecture
    image
    created_at
    updated_at
}

entity SakeDetail {
    + id [PK]
    ---
    # sake_id [FK]
}


@enduml